### PR TITLE
Featuree/add current time to message

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
This time it works!

### CODE REVIEW

**Comment by tdziadkiewicz** [comment]
Upon test time shown is 00:00:00 feature still not working will not merge

**Comment by tdziadkiewicz** [comment]
Upon manual testing feature works correctly, please remove obselate files

**Comment by tdziadkiewicz** [comment]
This fix has obselate commits please reduce the ammount

**Comment by gdziadkiewicz** [comment]
Done

**Pull request merged**
